version: '2'

services:
  automata_jl:
    image: automata_jl:latest
    command: "bash -c 'jupyter lab --no-browser --ip=* --port=9000 --allow-root --notebook-dir=/home --NotebookApp.token=\"\"'"
    volumes:
      - ./:/home
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - 9000:9000
    environment:
      - PATH=${PATH}:/root/.julia/v0.6/Conda/deps/usr/bin/
      - SHELL=/bin/bash
